import { EditorHapticEvent, AHAPPattern, AHAPEvent, AHAPParameterCurve, AHAPParameterCurveControlPoint } from '../types';

// Configuration constants for AHAP compliance
const TIME_PRECISION = 4; // 0.0001s precision
const PARAM_PRECISION = 3; // 0.001 value precision

// Helper: Round to specific decimal places to avoid floating point artifacts
const round = (num: number, precision: number): number => {
  const factor = Math.pow(10, precision);
  return Math.round((num + Number.EPSILON) * factor) / factor;
};

// Helper: Clamp values to valid AHAP ranges (usually 0.0 to 1.0)
const clamp = (num: number, min = 0, max = 1): number => {
  return Math.min(Math.max(num, min), max);
};

/**
 * AHAP Export Engine
 * A dedicated class responsible for compiling the internal editor state
 * into a validated, optimized Apple Haptic Audio Pattern (AHAP) file.
 */
export class AHAPExportEngine {
  private events: EditorHapticEvent[];

  constructor(events: EditorHapticEvent[]) {
    this.events = events;
  }

  /**
   * Generates the AHAP pattern object.
   */
  public generate(): AHAPPattern {
    // 1. Sort events chronologically
    const sortedEvents = [...this.events].sort((a, b) => a.startTime - b.startTime);

    // FIX: The `Pattern` property expects an array of objects, where each object
    // is either `{ Event: AHAPEvent }` or `{ ParameterCurve: AHAPParameterCurve }`.
    // The original type was incorrect.
    const patternItems: ({ Event: AHAPEvent } | { ParameterCurve: AHAPParameterCurve })[] = [];

    for (const evt of sortedEvents) {
      this.compileEvent(evt, patternItems);
    }

    return {
      Version: 1.0,
      Metadata: {
        Project: "Haptic Studio Export",
        Created: new Date().toISOString(),
        Description: "Generated by Haptic Studio Pro Core Engine"
      },
      Pattern: patternItems
    };
  }

  /**
   * Compiles a single editor event into AHAP Event + Curves
   */
  private compileEvent(evt: EditorHapticEvent, output: any[]) {
    const startTime = round(evt.startTime, TIME_PRECISION);
    const duration = round(evt.duration, TIME_PRECISION);
    
    // Detect if this should be treated as a continuous event
    // (Either explicit Continuous type, OR a Transient with user-defined duration)
    const isTransient = evt.type === 'Transient';
    const hasDuration = duration > 0.005; // Tolerance for "zero"
    const isEffectiveContinuous = evt.type === 'Continuous' || (isTransient && hasDuration);

    // 1. Create Base Event
    const ahapEvent: AHAPEvent = {
      EventType: isEffectiveContinuous ? 'HapticContinuous' : 'HapticTransient',
      Time: startTime,
      EventParameters: [
        { 
          ParameterID: 'HapticIntensity', 
          ParameterValue: clamp(round(evt.intensity, PARAM_PRECISION)) 
        },
        { 
          ParameterID: 'HapticSharpness', 
          ParameterValue: clamp(round(evt.sharpness, PARAM_PRECISION)) 
        }
      ]
    };

    if (isEffectiveContinuous) {
      // Continuous events must have a duration
      ahapEvent.EventDuration = Math.max(duration, 0.005);
    }

    // FIX: The AHAPEvent must be wrapped in an object with an "Event" key
    // to match the structure defined in AHAPPattern.
    output.push({ Event: ahapEvent });

    // 2. Create Parameter Curves (if applicable)
    // Only attach curves to continuous-style events to avoid engine warnings
    if (isEffectiveContinuous) {
      this.compileCurve(output, 'HapticIntensityControl', startTime, duration, evt.intensityCurve);
      this.compileCurve(output, 'HapticSharpnessControl', startTime, duration, evt.sharpnessCurve);
    }
  }

  /**
   * Compiles a parameter curve, normalizing time and values
   */
  private compileCurve(
    output: any[], 
    parameterId: string, 
    startTime: number, 
    duration: number, 
    points: AHAPParameterCurveControlPoint[]
  ) {
    if (!points || points.length === 0) return;

    // Sort points by time
    const sortedPoints = [...points].sort((a, b) => a.Time - b.Time);

    // Map to AHAP Control Points
    const controlPoints: AHAPParameterCurveControlPoint[] = sortedPoints.map(p => {
      // Clamp time to event duration
      const t = clamp(p.Time, 0, duration);
      return {
        Time: round(t, TIME_PRECISION),
        ParameterValue: clamp(round(p.ParameterValue, PARAM_PRECISION))
      };
    });

    // Optimization: We could remove redundant collinear points here in a future version.

    output.push({
      ParameterCurve: {
        ParameterID: parameterId as any,
        Time: startTime,
        ParameterCurveControlPoints: controlPoints
      }
    });
  }
}

// --- Public Exports ---

export const generateAHAP = (events: EditorHapticEvent[]): AHAPPattern => {
  const engine = new AHAPExportEngine(events);
  return engine.generate();
};

export const downloadJSON = (data: object, filename: string) => {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};